### ISSUE TITLE
Skip-to button not clickable when using browser zoom

### ISSUE THREAD

**Issue by awkawk** [paypal/skipto#11]
This will be implementation specific, but it affects your sample page.  When you zoom in (ctrl+plus) and the skip to button sits directly above the page title text, the portion of the button that is above the text doesn't work with the mouse. 

![image](https://f.cloud.github.com/assets/4228257/2233185/d9608166-9b26-11e3-8383-c7f48b57643f.png)

In the screenshot above, when the pointer is on the link text it doesn't work, but if the pointer is to the left of that then it does.  

The issue is that the .inner class box is hiding the button from the mouse.  If the .inner class has z-index=-1 then this issue goes away (but this causes other problems).  

Sorry I don't have a fix to suggest but I noticed this and thought you'd want to know.

**Comment by mpnkhan** [comment]
Could you kindly check if this is working for you now? 
I zoomed multiple times on safar/chrome/firefox on mac and it worked for me.
