### ISSUE TITLE
Question around PR #103, re: landmark labels

### ISSUE THREAD

**Issue by CarlyGerard** [paypal/skipto#111]
@jongund We're hoping to start using this library on our university websites. I had a quick question around your change to naming landmark menu items as ARIA roles in PR #103, and thought this might be a good place to ask. It looks like those items were originally labeled "header," "footer," etc.

I gave a sneak peek of SkipTo to my team, using the landmark menu label defaults. Some were confused by the naming; they weren't sure what a "contentinfo" was--but they do know what a `<footer>` is and where they might go if they activate that.

My guess as a reason is to align the naming with technologies that expose these landmarks through ARIA--so it's a "banner" whether using native screen reader navigation or using SkipTo. I didn't want to assume though, so I'd like to hear if there's reasoning against labels like header/footer/aside I should consider. Thanks.

**Comment by jongund** [comment]
@CarlyGerard 
Sorry for the delayed response.
The HTML markup to create the `banner` and `contentinfo` landmarks are the `header` and `footer` element.
In assistive technology they are referred to as `banner` and `contentinfo`, so for better or worse I think consistency is best to use what the ARIA standards and practices call them.  If you disagree you can always override the default labels through configuration to use your naming preferences.
