### ISSUE TITLE
Ability to change z-index in skipto configuration

### ISSUE THREAD

**Issue by bryanjonker-illinois** [paypal/skipto#118]
One of our users noted that the skip-to is not going above our menu. Is there a way we can set the z-index on the skip-to so we can ensure this doesn't happen?

**Comment by bryanjonker-illinois** [comment]
I think adding this CSS fixes the issue. 
````
.skip-to [role=menu] {
    z-index: 5001!important;
}
````

**Comment by bryanjonker-illinois** [comment]
And I'm envisioning something like this for the settings:

````
var SkipToConfig = { 'settings': { 'skipTo': { displayOption: 'static', colorTheme: 'illinois', z-index: '5001' } } };
````

**Comment by brianteeman** [comment]
> I think adding this CSS fixes the issue.
> 
> ```
> .skip-to [role=menu] {
>     z-index: 5001!important;
> }
> ```

Why not just put that in the css of your web site?

**Comment by bryanjonker-illinois** [comment]
We can, but I was thinking it would be a good "quality of life" improvement

**Comment by brianteeman** [comment]
As this can be set in the site css as indicated above I wonder about the value of that change. It still wouldnt fix a site with a high z-index. If its going to be addressed in the script (and my 2c is that it shouldnt) then I agree with @bryanjonker-illinois and it should be a configurable setting

**Comment by brianteeman** [comment]
closed as addressed elsewhere
