### ISSUE TITLE
skip-to not working when using custom components

### ISSUE THREAD

**Issue by bryanjonker-illinois** [paypal/skipto#119]
We started changing our website to use custom components. When we wrapped everything in the ``<il-page>`` component, the skip-to no longer registered any headings in the page. Also, tabbing did not show the skip-to link -- you had to be on Chrome and use Alt-0 to display it. 

https://education.illinois.edu
https://education.illinois.edu/about/mission-vision

**Comment by brianteeman** [comment]
> Also, tabbing did not show the skip-to link 

Is that not your z-index problem?

**Comment by bryanjonker-illinois** [comment]
Ah, that was on a different site, but I think so. I guess the big issue is why are the headings not showing up?

**Comment by brianteeman** [comment]
yeah - not sure about that. @jongund will probably have a better idea. At a _guess_ I would look at the [css selectors](https://github.com/paypal/skipto#css-selectors-for-identifying-landmarks-and-headings)

**Comment by jongund** [comment]
@bryanjonker-illinois 
This is something that will addressed in a future version of SkipTo, probably version 4.3 since it will not allow the flexibility the current CSSS selector technique for identifying headings and landmarks to be used.

**Comment by brianteeman** [comment]
closed as addressed elsewhere
