### ISSUE TITLE
Please let us know if you use skipto and would like to be included in skipto Gallery

### ISSUE THREAD

**Issue by mpnkhan** [paypal/skipto#21]
If you use skipto and would like to be listed on http://paypal.github.io/skipto/ under "Skipto Gallery” please let us know. 

Leave a comment and url. 

Thanks
-PayPal Accessibility Team

**Comment by srinivasuchakravarthula** [comment]
Yes, I use it on http://srinivasu.org, and http://sgaccessibility.com

Also, you may want to include http://kickstartcabs.com
