### ISSUE TITLE
Greasemonkey script and landmarks

### ISSUE THREAD

**Issue by marcjohlic** [paypal/skipto#24]
Hi - I was trying out the Greasemonkey version of SkipTo, but I'm only seeing headings for a page in the SkipTo menu - not any of the ARIA landmarks.

Is there anything I need to do to the Greasemonkey code to enable the display of landmarks in the menu?

**Comment by vick08** [comment]
uite likely, the greecemonkey script has not been updated to reflet the latest changes.
 


     On Monday, May 4, 2015 8:13 AM, Marc Johlic <notifications@github.com> wrote:
   
 

 Hi - I was trying out the Greasemonkey version of SkipTo, but I'm only seeing headings for a page in the SkipTo menu - not any of the ARIA landmarks.
Is there anything I need to do to the Greasemonkey code to enable the display of landmarks in the menu?—

**Comment by mpnkhan** [comment]
Please remove old skipto.js from GM->Manage user scripts and install the latest from paypal.github.io/skipto/downloads/js/SkipTo.user.js. I did and tried it on http://www.w3.org/TR/wai-aria-practices/# , its working.
