### ISSUE TITLE
Script throws exception when page has main tag without role attribute

### ISSUE THREAD

**Issue by apuchkov** [paypal/skipto#26]
This is what happened to me:

I followed instructions to add minimized SkipTo script to the page with default options and it was throwing exception: 

      Uncaught TypeError: Cannot read property 'replace' of null           SkipTo.min.js:7

The page had <main> element, without role="main" attribute. However, after some debugging I discovered that SkipTo script expects role attribute to be always set.

I see a couple of options here:
 - expect that roles attribute can be missing and add some checks
 - have more developer friendly exception message

**Comment by jongund** [comment]
This has been fixed
