### ISSUE TITLE
Skip to js not  compatible with IE8

### ISSUE THREAD

**Issue by anandpearl** [paypal/skipto#30]
Hi , It is showing error in IE8. 

"Webpage error details

Message: 'Window' is undefined
Line: 7
Char: 5
Code: 0
URI: http://****.com/wp-content/plugins/skip-to/js/SkipTo.min.js?ver=2.0.0
"

**Comment by moekraft** [comment]
Hello, 
Investigating. Check out the modified version, headingNavigation by James Nurthen, https://github.com/jnurthen/headingNavigation. James updated skipTo to work with iframes and turned off landmark navigation for a targeted solution. This does work in IE8 document mode. The shimIE.js file should take care of backward compatibility. Comparing the two plugins to ascertain what was changed in headingNavigation that fixed the IE8 error in skipTo. Will keep you posted on the findings. 

Moe

**Comment by brianteeman** [comment]
Closing this old issue. IE8 is dead and buried as a browser now
