### ISSUE TITLE
Edits to work with SPAs (and feasibility for long-term inclusion in library)

### ISSUE THREAD

**Issue by kidatsy** [paypal/skipto#43]
Hi there!

First off, thank you for your work on this! It is much-needed.

I work for Crisis Text Line (https://crisistextline.org) - we are a national 24/7 crisis support line that operates mainly over SMS. We are looking at implementing this great library to increase the accessibility of our main web app, where our crisis counselors take conversations. It is a single-page app though, and the model of following the path to the `#ID` anchor of each ID element doesn't quite work for our purposes. I've made a number of changes to accommodate the functionality we need, which you can see here: https://github.com/CrisisTextLine/skipto/pull/1. That includes:
- Including a custom description of each ID item
- Ability to define a custom callback to be triggered on navigating to an item
- Additional booleans for focusing on an element rather than navigating to it, appending the `#` to the current path, and enumerating each element, rather than displaying the element type.

They are all implemented in a way that allows for normal operation of previously defined implementations of the library to continue working as they have.

I'm happy to put up a PR against your main fork of the repo, but I had a couple of questions before we do that:
- How likely would it be that you would be to include this kind of functionality in the library?
- If so, is this the best way of going about it? We don't want to be in a situation where we make these changes, but they remain just in our fork of it, resulting in us not getting the subsequent updates.
- I've got it working with the React side of our app with some tweaks, but are there any plans for React-friendliness on the horizon?

Thank you again!

**Comment by mpnkhan** [comment]
I think this is a nice feature and the code is neat and better. 
@jongund @nhoyt Thoughts?

**Comment by kidatsy** [comment]
Hi @mpnkhan et al (including @jongund and @nhoyt), checking back in with this, post-holidays. Would love to have some feedback - or would it be better to just go ahead and make a PR now? Thanks!

**Comment by mpnkhan** [comment]
Yes Please raise a PR..

**Comment by kidatsy** [comment]
Great! PR pulled: https://github.com/paypal/skipto/pull/44
