### ISSUE TITLE
SkipTo Nav port to Drupal 8

### ISSUE THREAD

**Issue by C13L0** [paypal/skipto#46]
It would be greatly appreciated to port SkipTo Nav to Drupal 8. 
https://www.drupal.org/project/skipto

**Comment by mgifford** [comment]
I still don't get why this is better than what is in Drupal Core already.

**Comment by brianteeman** [comment]
Looks like the version you have over at drupal.org is very very out of date. The current repo here does have some wordpress and drupal code BUT its not been tested for a long time and will be removed (when I find a spare moment)

**Comment by mgifford** [comment]
Apparently I had come across this module at one point https://www.drupal.org/project/skipto/issues/2634774

Noted the need to upgrade.

**Comment by brianteeman** [comment]
That looks about the time I showed it to Andrew - maybe he mentioned it.
