### ISSUE TITLE
expand menu on down arrow

### ISSUE THREAD

**Issue by robfentress** [paypal/skipto#47]
I think an expected behavior for the menu button would be for the menu to appear when the down arrow is pressed while the button has focus.  This is what is demonstrated in [the most relevant example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menu-button/menu-button-links.html) in the Aria Authoring Practices.  Please consider adding this affordance.

**Comment by jongund** [comment]
@robfentress 
The latest version of SKipTo supports the APG.
