### ISSUE TITLE
Landmarks / Localization

### ISSUE THREAD

**Issue by webdesignweisshart** [paypal/skipto#48]
In my settings I use
"landmarks"    : "[role=navigation], [role=search]",
In the dropdown menu this is listed as:
Search:
Nav:

Is it possible to modify these items to e.g. 
Seiteninterne Suche
Navigation
<img width="325" alt="Bildschirmfoto 2020-05-02 um 16 24 15" src="https://user-images.githubusercontent.com/59532422/80866873-6cb26a80-8c91-11ea-9652-19c600621f59.png">

**Comment by jongund** [comment]
Yes,  All of the menuitem strings can be changed through (Skipto configuration options)[https://github.com/paypal/skipto/blob/main/README.md].  Let me know if you have any questions.  Send me your translated items and I will add an example on the README page.

**Comment by webdesignweisshart** [comment]
I did it. With version 4.0.1
Thanks for the help.
