### ISSUE TITLE
Exclude elements 

### ISSUE THREAD

**Issue by webdesignweisshart** [paypal/skipto#49]
I would like to exclude certain headings from being shown in the dropdown menu, to avoid duplicates.
Example:
My navigation contains a heading h2.
But the navigation is already displayed as skip link nav:.

**Comment by jongund** [comment]
You can use CSS selectors to identify which headings to include, see the documentation on creating a configuration object:
https://github.com/paypal/skipto/blob/main/README.md#css-selectors-for-identifying-landmarks-and-headings

**Comment by webdesignweisshart** [comment]
Thank you, I have found it in the meantime. It is not quite trivial, but it works as desired.
