### ISSUE TITLE
Update SkipTo to a new version with new features

### ISSUE THREAD

**Issue by jongund** [paypal/skipto#51]
@mpnkhan 

Nick and I have been working on a new version of SkipTo.js, you can see the code at the following URL:
https://github.com/a11y-tools/skipto

Is this something you would be interested in discussing as a update to version 2.1?

**Comment by mpnkhan** [comment]
I briefly went through the changes and i liked the changes. Its a right decision to remove IE6 support.  I have merged the changes

**Comment by jongund** [comment]
@mpnkhan 

Thanks for accepting the changes, we will need to get the GitHub Page updated:
http://paypal.github.io/skipto/

I plan to make a few more changes to the documentation and also to the default styling and positioning of the menu button.

Take care and hope all is going well for you,
Jon
