### ISSUE TITLE
Safari 14.0 issue on MacOS 10.15 

### ISSUE THREAD

**Issue by webdesignweisshart** [paypal/skipto#52]
Can't navigate thru menu-items with keyboard. Arrow down opens the Skipto dropdown menu, but subsequent arrow down closes it.

**Comment by jongund** [comment]
@webdesignweisshart 
Has this issue been resolved for you?

**Comment by webdesignweisshart** [comment]
@jongund I'm on version 4.0.1 and everything seems to work fine now. Thanks al lot.
