### ISSUE TITLE
Version numbers

### ISSUE THREAD

**Issue by brianteeman** [paypal/skipto#72]
You need to change the version number as you have renamed numerous labels and classes. This means that anyone who was customising those labels or classes loses their customisations.

The rules of semantic versioning state that you can only make backwards compatible changes in a new major release (see https://docs.npmjs.com/about-semantic-versioning)

That means that 3.1.4 **must** be version 4.0.0

**Comment by mpnkhan** [comment]
Agree, I'm in Festival mood though :-). skipto@4.0.0 published

**Comment by brianteeman** [comment]
thank you

**Comment by brianteeman** [comment]
Surely there is more to it than just changing the version number in the package.json

Dont you need to rebuild as well ?

**Comment by mpnkhan** [comment]
Sine Jon compiled it, i didn't compile. But yes after versioning should have built and publish. 
+ skipto@4.0.1
