### ISSUE TITLE
Discussion of future development of SkipTo

### ISSUE THREAD

**Issue by jongund** [paypal/skipto#73]
@mpnkhan 
Is there a time we could meet to talk about further SkipTo development?
I am interested in learning more about any used or plans PayPal has for SkipTo.
We are thinking of some significant changes and would like to discuss them with you and your team.

Jon

**Comment by mpnkhan** [comment]
PayPal has no plan, support for use for SkipTo or any of accessibility open source libraries published at  http://paypal.github.io/a11y/ . I'm doing it on my personal time.   Let's talk on Google Duo.

**Comment by brianteeman** [comment]
I would be interested in helping as well now that this will be part of  core Joomla

**Comment by mpnkhan** [comment]
@brianteeman  That would be nice.  
@jongund, i would suggest opening up a github ticket and continue the discussion. Gives us more ideas from other contributors as well.
