### ISSUE TITLE
Question: Basic: No Actions and no heading level shortcuts

### ISSUE THREAD

**Issue by brianteeman** [paypal/skipto#75]
![image](https://user-images.githubusercontent.com/1296369/104788980-a5489480-578b-11eb-8abe-0afffcd19d0f.png)

```
                    enableActions: false,
                    enableHeadingLevelShortcuts: false,
```

In this scenario is there really any point in displaying the mofn 
I

**Comment by brianteeman** [comment]
At the same time is there no option to be able to display everything all the time without the actions

**Comment by jongund** [comment]
@brianteeman 
We don't want people to think that the list of landmarks and heading are all the headings or all the landmarks on a page.
It could be confusing to people if they know there are more than what they see.

**Comment by brianteeman** [comment]
OK. I guess.

What about an option to show everything without the limit

**Comment by jongund** [comment]
@brianteeman 
You can configure the landmark and heading selectors to show everything onload if you want to.
But SKipTo's primary purpose is for providing keyboard access to important areas on the page, so shorter lists make for more efficient keyboard navigation.

**Comment by jongund** [comment]
what did you use as selectors?

**Comment by jongund** [comment]
@brianteeman 
Based on feedback from many people, the actions menu and the M of N are disabled by default in version 4.04.
