### ISSUE TITLE
Version Numbers

### ISSUE THREAD

**Issue by brianteeman** [paypal/skipto#78]
It's great to see so much activity in the last few months. When I first discovered this repo there was nothing.

There are currently 600+ weekly downloads from npmjs.com and when Joomla v4 is released in late Q1 that will add another huge increase in the users.

As a result updates, version numbers and releases need to be considered as it impacts a lot of people.

For version numbers its important that they are used correctly as users will have settings in their package.json that will be impacted.

If it is a bug fix then you just increment **x.x.Y**
If it is a new feature that doesn't break anything then you increment **x.Y.0**
If it is a new feature or bug fix that does break things then you increment **Y.0**

When there are multiple people submitting pull requests that may or may not be merged in order then it makes sense that you do not increment the version number at all in your pull request. Instead a separate pull request for version number changes when a new release is made. Currently it looks like each merge is resulting in a new release. That's fine but it doesn't have to be that way and it might be simpler to only do releases separately to merges, perhaps on a monthly basis.

**Comment by mpnkhan** [comment]
This makes sense. @jongund

**Comment by jongund** [comment]
@brianteeman 
Can you send me a link to a Joomla based website where I can see the use of SkipTo being used?

**Comment by brianteeman** [comment]
Not yet as it will be in version 4.0 of Joomla which will be released in approx 4 -8 weeks. 
If you want I can set up a site and give you access to it to test but I would need your email address to send you the username and password.

**Comment by jongund** [comment]
@brianteen
My e-mail address is: jongund@illinois.edu.

# Changes in Near Future
I don't anticipate any changes to SkipTo in the near future, except for bug fixes.

## User Customization Request
We have received feedback from people with disabilities wanting to be able to customize what's in the menu based on their preferences or content related to a particular website.  Not sure exactly how this fits into the current SkipTo design and it would need to probably set and use cookies, but this sounds to me more like a browser extension, but it may lead to some changes in SkipTo.  Just exploring the ideas right now.

## CDN  
We are also setting up a CDN to make it easier for people to reference the most current version of SkipTo.js.  Not sure how this impacts inclusion with Joomla, but wanted to let you know.

**Comment by jongund** [comment]
Is the current npm working for you?
Does the code that generates the npm need some updating, since I have not changed any of the code for creating the npm version.
