### ISSUE TITLE
Moving to "skipto' organization for future development

### ISSUE THREAD

**Issue by jongund** [paypal/skipto#81]
@mpnkhan 
We have secured GitHub ['skipto' organization](https://github.com/skipto) for use in developing the SkipTo script and a SkipTo extension we are looking at developing, which would be more of an assistive technology for keyboard users.
Right now we are using a fork of the PayPal SkipTo repository and doing Pull requests.
Wondering what your thoughts are about moving code development to a new 'SkipTo` organization.
PayPal contributions and authorship would be documented in the new repository.
The 'SkipTo' organization will hopefully attract new people to participate in development and testing, and make it easier  for people to find information on SkipTo.

Look forward to hearing your thoughts and concerns.

**Comment by mpnkhan** [comment]
I'm okay with moving code development to a new 'SkipTo` organization.  @brianteeman what do you think?

**Comment by jongund** [comment]
@mpnkhan 

What is the best way to setup the new repository on (https://github.com/skipto)[https://github.com/skipto] organization:
1. Clone the current repository to the new location, leaving this repository intact. 
2. Move this repository to the new location, so this would be gone.
3. Start the new repository from where this one left off, basically I thnk that would be a fork of this repository.

We want to make sure we keep the history of PayPal and other contributors and credit to PayPal Accessibility Team for the original work on SkipTo.js.

**Comment by mpnkhan** [comment]
Fork this repository to the new one. We can leave a message sayinsg this is no more maintained and should redirect to the new skipto. Also i think i need to change npmrc settings to point to the new one.

**Comment by brianteeman** [comment]
I may be wrong here but looking at other projects on npmjs you may need to rename it

> I'm okay with moving code development to a new 'SkipTo` organization. @brianteeman what do you think?

Have paypal approved this?

**Comment by mpnkhan** [comment]
Thats the reason i suggested forking this repo to new location and marking existing as obselete.

**Comment by jongund** [comment]
@mpnkhan 
This sounds good to me, but let me talk to my colleague to see what he thinks.

**Comment by mpnkhan** [comment]
@jongund done. Please check your mail and accept it
