### ISSUE TITLE
NPM release

### ISSUE THREAD

**Issue by brianteeman** [paypal/skipto#83]
Would it be possible to push 4.0.3 to npm please

**Comment by mpnkhan** [comment]
+ skipto@4.0.3 Done. 

Took a while, sorry. 
My personal machine stopped supporting nodejs as the os is old. Office machine was blocked with zscaler upgrade. Had to request special access to release. If you can share your npm login id i would add you as contributor.

**Comment by brianteeman** [comment]
I use the same login ID everywhere ;)
