### ISSUE TITLE
RTL issue

### ISSUE THREAD

**Issue by brianteeman** [paypal/skipto#84]
https://github.com/paypal/skipto/blob/fdeea8a47a98f0e712090ce4fefbcd3a223d20b7/src/css/SkipTo.template.css#L1-L5

If you have skipto enabled on a website using an RTL language then the css above has undesirable effects as it results in expanding the visible page width by 3000em

See https://jongund.brianstest.site/ for a demo

**Comment by jongund** [comment]
@brianteeman 
When the button gets focus, the top and left properties are set to values in the visible window, see lines 7-12:

```html
.skip-to,
.skip-to.popup.focus {
  position: absolute;
  top: 0;
  left: $positionLeft;
}
```

Do you have a different way to move content off the visible window, but still visible to assistive technologies?

**Comment by brianteeman** [comment]
@jongund Yes I understand how it works - it just doesn't work the same on an RTL site

Perhaps a more robust solution would be to use the approach of webaim.org which as you can see uses a negative top position so it will work on LTR and RTL
```

/* Template styles */

#skiptocontent a {
	padding:6px;
	position: absolute;
	top:-40px;
	left:0px;
	color:white;
	border-right:1px solid white;
	border-bottom:1px solid white;
	border-bottom-right-radius:8px;
	background:#BF1722;
        z-index: 100;
}

#skiptocontent a:focus {
	position:absolute;
	left:0px;
	top:0px;
	outline-color:transparent;	
}

```

**Comment by jongund** [comment]
Changed to:
```html
 .skip-to.popup { 
   position: absolute; 
   top: -30em; 
   left: -0; 
 } 
```

**Comment by brianteeman** [comment]
thanks
