### ISSUE TITLE
4.0.4 Release

### ISSUE THREAD

**Issue by brianteeman** [paypal/skipto#87]
For your information 4.0.4 broke my joomla installation in the following ways

1.  To enable language translation we were using the documented method
The removal of buttonTitle and buttonTitleWithAccesskey broke the configuration object

2. Enable Actions
As explained before this change broke the installations by changing the default behaviour

**Comment by jongund** [comment]
Sorry it broke your code.
I think there should be a testing system for any updates to the code.
Do you think the `buttonTitle` and `buttonTitleWithAccesskey` properties should be supported but deprecated configuration parameters?

**Comment by brianteeman** [comment]
I said it would break. I said breaking changes meant that the version number should be incremented according to semver as a result. Dont know what else I could have done

**Comment by jongund** [comment]
I just created pull request that restores supports `buttonTitle` and `buttonTitleWithAccesskey`.
