### ISSUE TITLE
Ensure website provides a demo of the skipto functionality

### ISSUE THREAD

**Issue by mgifford** [paypal/skipto#93]
I went here http://paypal.github.io/skipto/

Wasn't able to get the skip link working. Maybe I'm doing something wrong though. 

Does it work in the demo?

**Comment by brianteeman** [comment]
Hi Mike

It looks like the "demo" is out of sync with the repo and is indeed broken.

In the meanwhile you can test it on any of the live sites listed in the readme https://github.com/paypal/skipto#visible-menu-button-default and https://github.com/paypal/skipto#popup-menu-button

I have imple,mented this as a core plugin for joomla 4 and it is enabled by default in the joomla 4 admin

**Comment by brianteeman** [comment]
It is better than what anyone other than Joomla does ;)

Visible by default is an option as an alternative to visible on hotkey or visible on keyboard focus

**Comment by brianteeman** [comment]
The demo is now working
