### ISSUE TITLE
The WAVE accessibility tool flags an error "1 X Broken ARIA menu".

### ISSUE THREAD

**Issue by webdesignweisshart** [paypal/skipto#94]
The WAVE accessibility tool by https://wave.webaim.org/ shows an error "1 X Broken ARIA menu".
The cause is as follows:

WAVE evaluates the initial state of the page after it loads, and at that moment in time, the ARIA menu is not populated, so thus it is flagged as being an error.

Wouldn't it be better to not generate the empty ARIA menu until the menu is actually triggered – in this case WAVE would not detect the empty ARIA menu or present the error.

The issue can be reproduced on my site https://webdesign.weisshart.de, using the online WAVE tool at https://wave.webaim.org/

**Comment by brianteeman** [comment]
This has been resolved with the release of 4.1.2
